In [1]:
import numpy
import seaborn as sns
import pandas as pd
import matplotlib
from matplotlib import *
%matplotlib inline

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [2]:
in_labels = pd.read_csv('data/input-data-labels.csv',encoding='utf-8')
in_labelling = pd.read_csv('data/input-data-labeling.csv',encoding='utf-8')

In [3]:
import sys
reload(sys)
sys.setdefaultencoding('utf8')

In [4]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 1000) 

In [5]:
name_features = vectorizer.fit_transform(in_labelling['name'])
name_features = name_features.toarray()

In [6]:
numpy.count_nonzero(name_features)

563671

In [7]:
name_df = pd.DataFrame(name_features)

In [8]:
name_df.head()

0    1    2    3    4    5    6    7    8    9   ...   990  991  992  993  \
0    0    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0 ...     0    0    0    0   

   994  995  996  997  998  999  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 1000 columns]

In [9]:
del in_labelling['name']
del in_labelling['description']
del in_labelling['id']

In [10]:
label_targets = in_labelling['labels']

In [11]:
del in_labelling['labels']

In [12]:
in_labelling.head()

price              shop                brand
0  84.949997  Herrenausstatter  Herrenausstatter.de
1  24.950001  Herrenausstatter               Jockey
2  24.950001  Herrenausstatter               Jockey
3  39.950001  Herrenausstatter               Jockey
4  19.950001  Herrenausstatter                  HOM

In [13]:
from sklearn import preprocessing
# Discreet value integer encoder
label_encoder = preprocessing.LabelEncoder()

In [14]:
in_labelling['shop'] = label_encoder.fit_transform(in_labelling['shop'])
in_labelling['brand'] = label_encoder.fit_transform(in_labelling['brand'])

In [15]:
in_labelling.head()

price  shop  brand
0  84.949997   117   1713
1  24.950001   117   1941
2  24.950001   117   1941
3  39.950001   117   1941
4  19.950001   117   1645

In [16]:
feature_df = pd.concat([in_labelling,name_df],axis=1)

In [17]:
feature_df.head()

price  shop  brand  0  1  2  3  4  5  6 ...   990  991  992  993  994  \
0  84.949997   117   1713  0  0  0  0  0  0  0 ...     0    0    0    0    0   
1  24.950001   117   1941  0  0  0  0  0  0  0 ...     0    0    0    0    0   
2  24.950001   117   1941  0  0  0  0  0  0  0 ...     0    0    0    0    0   
3  39.950001   117   1941  0  0  0  0  0  0  0 ...     0    0    0    0    0   
4  19.950001   117   1645  0  0  0  0  0  0  0 ...     0    0    0    0    0   

   995  996  997  998  999  
0    0    0    0    0    0  
1    0    0    0    0    0  
2    0    0    0    0    0  
3    0    0    0    0    0  
4    0    0    0    0    0  

[5 rows x 1003 columns]

In [18]:
def get_level1(df_text):
    split_text = df_text.split(',')
    return split_text[0]

In [19]:
label_targets2 = label_targets.apply(get_level1)

In [20]:
label_targets2 = label_encoder.fit_transform(label_targets2)

In [21]:
label_targets2[:200]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 1, 1, 3, 3, 1, 3, 1, 1, 3, 1, 1, 3, 3, 3, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 3, 1, 1, 3, 1, 3, 1, 1, 1, 1, 3, 0, 3, 1, 1, 1, 1, 1,
       1, 3, 3, 3, 3, 1, 1, 3, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1,
       1, 1, 0, 0, 3, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       3, 3, 1, 3, 3, 1, 3, 3, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 1, 3, 1, 1,
       1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
       1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [22]:
from sklearn import cross_validation
from sklearn import ensemble

In [23]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(feature_df,label_targets2,test_size=0.2)

In [24]:
pa_classifier = ensemble.RandomForestClassifier()

In [25]:
pa_classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, compute_importances=None,
            criterion='gini', max_depth=None, max_features='auto',
            min_density=None, min_samples_leaf=1, min_samples_split=2,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0)

In [26]:
test_pred = pa_classifier.predict(X_test)

In [27]:
from sklearn import metrics
metrics.accuracy_score(y_test,test_pred)

0.97202500000000003

In [28]:
l1_feature = pa_classifier.predict(feature_df)

In [29]:
metrics.accuracy_score(label_targets2,l1_feature)

0.99306000000000005

In [30]:
l1_df = pd.Series(l1_feature)
l1_df.name='level1'

In [31]:
l2_feature_df = pd.concat([feature_df,l1_df],axis=1)

In [32]:
l2_feature_df.head()

price  shop  brand  0  1  2  3  4  5  6   ...    991  992  993  994  \
0  84.949997   117   1713  0  0  0  0  0  0  0   ...      0    0    0    0   
1  24.950001   117   1941  0  0  0  0  0  0  0   ...      0    0    0    0   
2  24.950001   117   1941  0  0  0  0  0  0  0   ...      0    0    0    0   
3  39.950001   117   1941  0  0  0  0  0  0  0   ...      0    0    0    0   
4  19.950001   117   1645  0  0  0  0  0  0  0   ...      0    0    0    0   

   995  996  997  998  999  level1  
0    0    0    0    0    0       1  
1    0    0    0    0    0       1  
2    0    0    0    0    0       1  
3    0    0    0    0    0       1  
4    0    0    0    0    0       1  

[5 rows x 1004 columns]

In [33]:
def get_level2(df_text):
    split_text = df_text.split(',')
    return split_text[1]

In [34]:
l2_label_targets = label_targets.apply(get_level2)

In [35]:
l2_label_targets = label_encoder.fit_transform(l2_label_targets)

In [36]:
l2_label_targets[:10]

array([17, 20, 51, 17, 51,  0,  0,  0,  0,  0])

In [37]:
l2_X_train,l2_X_test,l2_y_train,l2_y_test = train_test_split(l2_feature_df,l2_label_targets,test_size=0.2)

In [38]:
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier.fit(l2_X_train,l2_y_train)

RandomForestClassifier(bootstrap=True, compute_importances=None,
            criterion='gini', max_depth=None, max_features='auto',
            min_density=None, min_samples_leaf=1, min_samples_split=2,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0)

In [39]:
sec_preds = rf_classifier.predict(l2_X_test)

In [40]:
metrics.accuracy_score(l2_y_test,sec_preds)

0.77095000000000002

In [41]:
sec_preds[:100],l2_y_test[:100]

(array([61, 30, 61, 18, 61, 20, 62, 48, 31, 61, 61, 19, 19, 31, 31, 56, 24,
        61, 14, 42, 14, 20, 56,  4, 22, 31, 61,  0, 35, 31, 19, 22, 68, 61,
        18, 43, 56, 51, 31, 56, 56,  0, 18, 61, 17, 56, 68, 18, 14, 31, 61,
        61, 61, 18, 68, 22, 31, 18, 24, 24, 61, 12, 61, 31, 31, 18, 31, 14,
        40,  0, 13, 18, 68, 22, 48, 68, 18, 48, 48, 56, 31, 61, 56,  1, 31,
        18, 18, 31, 68, 18,  0, 31, 56, 18, 61, 18, 56,  1, 68, 56]),
 array([61, 31, 61, 18, 61, 20, 62, 48, 30, 61, 61, 19, 19, 14, 30, 56, 24,
        61, 14, 42, 14, 20, 56,  4, 22, 31, 48,  0, 35, 31, 43, 22, 68, 61,
        18, 43, 56, 51, 18, 56, 56,  0, 18, 61, 17, 56, 68, 18, 14, 18, 61,
        61, 61, 18, 68, 22, 56, 18, 24, 24, 61, 12, 61, 31, 14, 18, 40, 14,
        40, 20, 48,  2, 68, 22, 48, 24, 18, 61, 48, 56, 18, 61, 56,  1, 18,
        31, 31, 56, 68, 18,  0, 31, 56, 18, 61, 18, 56,  1, 20, 56]))

In [42]:
l2_label_targets[:100]

array([17, 20, 51, 17, 51,  0,  0,  0,  0,  0, 51, 68,  0,  0,  0,  0,  0,
        1, 62,  0, 20, 20, 20, 51,  1,  1,  1, 31, 20, 20, 40, 56,  1, 31,
       68,  1, 30, 51, 51, 56, 14, 14, 22, 20, 20, 51, 22, 51,  0, 51, 31,
       14, 51,  1, 31,  0, 31, 51, 51, 68, 24, 18, 48, 56, 68, 20, 20, 68,
        1, 51, 18, 56, 56, 56, 20, 41, 56, 56, 43, 22, 22,  0, 56, 51, 51,
       51, 51, 56, 68, 22, 22, 51, 51, 51, 61, 61, 56, 22, 41, 43])